trigger: none

schedules:
  - cron: "0 20 * * *"
    displayName: "Daily 8:00 PM UTC Test Run"
    branches:
      include:
        - main
    always: true

pool: WD-BUILD-POOL  

jobs:
  - job: RunCypressTests
    timeoutInMinutes: 300  
    steps:
      # Install Node.js 
      - task: NodeTool@0
        inputs:
          versionSpec: "18.x" 
        displayName: "Install Node.js"

      # Install dependencies
      - script: npm install
        displayName: "Install Dependencies"

      # Clean reports 
      - script: npx rimraf@4.4.1 cypress/reports
        displayName: "Clean Reports Directory"
        continueOnError: true  

      # Create reports directories
      - script: mkdir cypress\reports\ && mkdir cypress\reports\mocha && mkdir cypress\reports\windeed-e2e-report
        displayName: "Create Reports Directories"
        continueOnError: true  

      # Run Cypress tests
      - script: npx cypress run || echo "Cypress tests completed with failures, proceeding"
        displayName: "Run Cypress Tests"
        continueOnError: true  

      # Combine Mocha JSON reports
      - script: npx mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/windeed-e2e-report/report.json
        displayName: "Combine Mocha Reports"
        continueOnError: true  

      # Generate HTML report
      - script: npx marge cypress/reports/windeed-e2e-report/report.json -f report -o cypress/reports/windeed-e2e-report --cdn true --inline false --scripts https://unpkg.com/mochawesome-report-generator@6.2.0/dist/app.js --styles https://unpkg.com/mochawesome-report-generator@6.2.0/dist/app.css
        displayName: "Generate HTML Report"
        continueOnError: true  

      # Zip the report directory
      - script: powershell.exe Compress-Archive cypress\reports\windeed-e2e-report cypress\reports\windeed-e2e-report.zip -Force
        displayName: "Zip Reports"
        continueOnError: true  

      # Send email with report
      - script: |
          node "./SendReport.js"
        displayName: "Email Report"
        continueOnError: true  

      # Upload the zipped report as an artifact
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: "cypress/reports/windeed-e2e-report.zip"
          artifactName: "cypress-report"
        condition: succeededOrFailed()  
        displayName: "Upload Test Report"